name: Update EC2 Instances

on:
  push:
    branches:
      - main

jobs:
  update_ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update EC2 Instance 1
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceids,Values=i-01eb6bcd6cd92a12d" \
            --parameters commands="cd /var/www/html/news && git pull" \
            --region us-east-1 \
            --query "Command.CommandId" \
            --output text

      - name: Update EC2 Instance 2
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceids,Values=i-05d58d2a307389dce" \
            --parameters commands="cd /var/www/html/news && git pull" \
            --region us-west-1 \
            --query "Command.CommandId" \
            --output text
