name: Update EC2 Instances

on:
  push:
    branches:
      - main

jobs:
  update_ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install SSH Client
        run: sudo apt-get install openssh-client -y

      - name: Prepare SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 Host Keys
        run: |
          ssh-keyscan 34.207.241.206 >> ~/.ssh/known_hosts
          ssh-keyscan 3.101.29.155 >> ~/.ssh/known_hosts

      - name: Update EC2 Instance 1
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@34.207.241.206 'cd /var/www/html/news && git pull'

      - name: Update EC2 Instance 2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@3.101.29.155 'cd /var/www/html/news && git pull'
