name: Update EC2 with GitHub changes

on:
  push:
    branches:
      - main  

jobs:
  update_ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Sync code to EC2 (Instance 1)
      uses: appleboy/scp-action@master
      with:
        host: 34.207.241.206
        username: ${{ secrets.EC2_USERNAME }}  
        key: ${{ secrets.EC2_SSH_KEY }}  
        source: "." 
        target: "/var/www/html/news"  

    - name: Sync code to EC2 (Instance 2)
      uses: appleboy/scp-action@master
      with:
        host: 3.101.29.155
        username: ${{ secrets.EC2_USERNAME }}  
        key: ${{ secrets.EC2_SSH_KEY }}  
        source: "." 
        target: "/var/www/html/news"
