name: Update EC2 Instances

on:
  push:
    branches:
      - main

jobs:
  update_ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install SSH
        run: sudo apt-get install openssh-client -y

      - name: Copy SSH Key
        run: |
          sudo mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | sudo tee ~/.ssh/id_rsa > /dev/null
          sudo chmod 600 ~/.ssh/id_rsa
          sudo sh -c "ssh-keyscan 34.207.241.206 >> ~/.ssh/known_hosts"
      
      - name: Update EC2 Instance 1
        run: |
          sudo ssh -v ubuntu@34.207.241.206 'cd /home/ubuntu/news && git pull'

      - name: Update EC2 Instance 2
        run: |
          sudo ssh -v ubuntu@3.101.29.155 'cd /home/ubuntu/news && git pull'
