name: Update EC2 with GitHub changes

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  update_ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Sync code to EC2
      uses: appleboy/scp-action@master
      with:
        host: 34.207.241.206
        username: ${{ secrets.EC2_USERNAME }}  # Add your EC2 username as a secret
        key: ${{ secrets.EC2_SSH_KEY }}  # Add your SSH key as a secret
        source: "."  # Path to your local code repository
        target: "/var/www/html/news"  # Path on your EC2 instance
