name: Update EC2 Instances

on:
  push:
    branches:
      - main

jobs:
  update_ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Authenticate with OIDC via AWS
        id: oidc_auth
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::854755582447:role/githubaction_terraform
          aws-region: us-east-1

      - name: Update EC2 Instance 1
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceids,Values=34.207.241.206" \
            --parameters commands="cd /var/www/html/news && git pull" \
            --region us-east-1 \
            --query "Command.CommandId" \
            --output text

      - name: Update EC2 Instance 2
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceids,Values=3.101.29.155" \
            --parameters commands="cd /var/www/html/news && git pull" \
            --region us-west-1 \
            --query "Command.CommandId" \
            --output text
