name: Deploy to EC2 Instances

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 Instances
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2 Instance 1
        uses: appleboy/ssh-action@master
        with:
          host: 34.207.241.206
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo rsync -avz --delete /var/www/html/news ubuntu@34.207.241.206:/var/www/html/news
            # Additional commands for permissions, restart, etc.

      - name: Deploy to EC2 Instance 2
        uses: appleboy/ssh-action@master
        with:
          host: 3.101.29.155
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo rsync -avz --delete /var/www/html/news ubuntu@3.101.29.155:/var/www/html/news
            # Additional commands for permissions, restart, etc.
